title: p5Catalyst Docs
description: Documentation for p5Catalyst.

# theme: jekyll-theme-slate
minima:
  skin: auto

source: docs
defaults:
  -
    scope:
      path: ""
    values:
      layout: default